### ISSUE TITLE
securityAgent.compliance.enabled: true causes agents to crashloopbackoff

### ISSUE THREAD

**Issue by joesteffee** [DataDog/helm-charts#1014]
**Describe what happened:**
Enabling agents.securityAgent.compliance.enabled: true starts up pods with securityContext set in the security-agent container. All of the processes in this container run as root, and /etc/datadog-agent/auth/token is set to 400 with the owner as id 101 or "ddagent" user. The security-agent pod does not have access to this token and crashes the whole pod repeatedly on startup

**Describe what you expected:**
Not crashing, having proper access to the token

**Steps to reproduce the issue:**
set agents.securityAgent.compliance.enabled: true on latest helm chart (3.25.5)

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes 1.24.10 on EKS

**Comment by levan-m** [comment]
Hello,

I'm unable to reproduce the issue. Here are the steps I followed:

Created EKS Fargate cluster, with Kubernetes v1.24.16.
```sh
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.16-eks-2d98532
WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1
```

Installed Agent default config and upgraded with the `datadog.securityAgent.compliance.enabled` override. (not `**agents**.securityAgent.compliance.enabled` as mentioned in the description, since it's invalid)
```sh
$ helm upgrade datadog datadog/datadog --version 3.25.5
--set datadog.apiKey=API_KEY
--set datadog.appKey=APP_KEY
--set datadog.securityAgent.compliance.enabled=true
```

Pods are running
```sh
$ kgp
NAME                                     READY   STATUS    RESTARTS   AGE
datadog-cluster-agent-6d96d6dbd6-hg6qt   1/1     Running   0          40m
datadog-xd48b                            4/4     Running   0          40m
```

Checking permission/ownership on token inside the `security-agent`, I see it's set to 600, not 400.
```
root@datadog-xd48b:/# ll /etc/datadog-agent/auth/token
-rw------- 1 101 root 64 Aug 25 17:17 /etc/datadog-agent/auth/token
```
I don't know if the 600 access makes things work in my environment, pod has been running for over 40min.

Could you please confirm if you are still facing the issue and provides steps to reproduce?

**Comment by levan-m** [comment]
Resolving since we haven't received any update for over a month. Feel free to reopen if the problem arises.
