### ISSUE TITLE
GKE Autopilot: orphaned datadog pods from deamon set

### ISSUE THREAD

**Issue by lkaluza-fadi** [DataDog/helm-charts#1142]
**Describe what happened:**
After a node get scaled up/down the deamon set try to deploy on that node. But in the meantime the nodes gets evicted and the result is an orphaned datadog pod.

**Describe what you expected:**
The datadog deamonset should be able to remove or terminate the pod gracefully before the node gets evicted

**Steps to reproduce the issue:**
After every node scale up/down on GKE Autopilot

**Additional environment details (Operating System, Cloud provider, etc):**
GKE Autopilot Version (1.26.5-gke.1400)

**Comment by valkum** [comment]
We are facing the same issues and are are in contact with Google support. According to their k8s engineers, the issues seems to be an invalid DaemonSet spec. See https://github.com/kubernetes/kubernetes/issues/118261#issuecomment-1572482716
The spec is accepted during creation but fails validation during shutdown.
The reason seems to be two env vars for `DD_PROVIDER_KIND`.

I am currently looking why the helm chart generates two `DD_PROVIDER_KIND` env vars.

**Comment by jtcressy** [comment]
+1 Currently facing the same issues on GKE Autopilot `v1.27.2-gke.1200`, dd chart version `3.33.7`

Looking forward to progress on @valkum's PR (#1143)

**Comment by bogdanmanate-kion** [comment]
We have the same issue on AKS (Version 1.27.3). Every time a node is scaled up and then removed there will be a datadog pod displayed as running on the node that was just removed. 
I'm currently using dd chart version: 3.38.3 and agent image tag: 7.47.1

**Comment by valkum** [comment]
> We have the same issue on AKS (Version 1.27.3). Every time a node is scaled up and then removed there will be a datadog pod displayed as running on the node that was just removed. I'm currently using dd chart version: 3.38.3 and agent image tag: 7.47.1

Did you check your deployed DaemonSet yaml's for duplicate values?
