### ISSUE TITLE
podLabelsAsTags support for custom metrics

### ISSUE THREAD

**Issue by rocketspacer** [DataDog/helm-charts#132]
**Describe what happened:**
I've configured `podLabelsAsTags` value when installing the datadog helm chart
https://github.com/DataDog/helm-charts/blob/master/charts/datadog/values.yaml#L87

I can see the pod labels appended as tags on the standard metrics like `kubernetes.memory.request`, `kubernetes.pods.running`, etc

I have an app that pushes stats using a custom metric: `envoy.http.downstream_rq_xx` via UDP to the hostPort of the datadog agent pods (deployed as DaemonSet) but there are no pod labels as tags on this metrics when I check on my dashboard.

**Describe what you expected:**
I want to know if `podLabelsAsTags` supports custom metrics and if there are any special steps I need to achieve this.

**Additional environment details (Operating System, Cloud provider, etc):**
Cloud Provider: AWS
Platform: AWS EKS
Kubernetes version: v1.18.9
Host OS: RHEL

**Comment by ahmed-mez** [comment]
Hi @rocketspacer 

You need to enable [Origin Detection](https://docs.datadoghq.com/developers/dogstatsd/?tab=kubernetes#origin-detection-over-udp) so the Datadog Agent can add Pod tags to your custom metrics.

To do so, please set `datadog.dogstatsd.originDetection` to `true` in your helm values, **and** set a `DD_ENTITY_ID` environment variable in your app Pod manifest

```
env:
    - name: DD_ENTITY_ID
      valueFrom:
          fieldRef:
              fieldPath: metadata.uid
```

If you're using an official and recent Dogstatsd client in your app, it will automatically read the value of `DD_ENTITY_ID` and forward it with the custom metrics to the Agent, which will rely on the value to attach the corresponding Pod tags.

[Origin Detection documentation](https://docs.datadoghq.com/developers/dogstatsd/?tab=kubernetes#origin-detection-over-udp)

I'm closing this issue because it is not really related to the Helm chart, but don't hesitate to [contact our solutions team](https://www.datadoghq.com/support/) to help you configure Origin Detection if needed.

Thanks!

**Comment by rocketspacer** [comment]
Shouldn't this default to true 😂

**Comment by ahmed-mez** [comment]
Hey @rocketspacer which **language** and **client version** you're using in your app? I can double check for you if it supports the feature.
Regarding enabling Origin Detection by default, thanks for the feedback! we can reevaluate this in future helm releases.

Thanks!

**Comment by rocketspacer** [comment]
I'm using [Envoy Dogstatsd stats sink](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/stats.proto#envoy-api-msg-config-metrics-v2-dogstatsdsink)

I think it uses a custom implementation, not in the official [libraries list](https://docs.datadoghq.com/developers/libraries) :'(

**Comment by ahmed-mez** [comment]
Sorry about that, it might be possible to contribute the feature to the envoy project though. @rocketspacer please feel to contact the [support team](https://www.datadoghq.com/support/) and submit a feature request.

**Comment by rocketspacer** [comment]
The **DD_ENTITTY_ID** value is just used to map to the tag [`dd.internal.entity_id`](https://github.com/DataDog/datadog-go/blob/master/statsd/statsd.go#L77) then I might be able to make this work. Thank you for all the help. I appreciate it. 🙇‍♂️
