### ISSUE TITLE
Windows node agent can't connect to Datadog cluster agent on EKS cluster

### ISSUE THREAD

**Issue by julianll1202** [DataDog/helm-charts#1512]
**Describe what happened:**
Windows node agent can't connect to Datadog cluster agent on EKS cluster.
```
Loading Errors
  ==============
    orchestrator_pod
    ----------------
      Core Check Loader:
        Could not configure check orchestrator_pod: orchestrator check is configured but the cluster name is empty

      Python Check Loader:
        unable to import module 'orchestrator_pod': No module named 'orchestrator_pod'
```

**Describe what you expected:**
Windows node agent connecting to datadog cluster agent and windows pods appearing on datadog's website.

**Steps to reproduce the issue:**
At the moment I do not know how to reproduce the issue.

**Additional environment details (Operating System, Cloud provider, etc):**
* **Agent version** 7.56.0
* **Helm chart version** 3.70.3
* **Kubernetes version** 1.29
* **Provider** AWS
* **Cluster type** EKS cluster

**Comment by fanny-jiang** [comment]
Hi @julianll1202, thank you for reporting this. In order to investigate this further, can you please open a [support ticket](https://docs.datadoghq.com/help/) referencing this github issue? Please provide a copy of your `values.yaml` file (with sensitive credentials redacted), and one of our agents will dig in and get back to your shortly. Thanks!

**Comment by julianll1202** [comment]
Hello, I have already  created a support ticket, my case id is 1814470

**Comment by tbavelier** [comment]
Closing as the associated ticket has been resolved and the underlying issue was at the Agent level: as displayed in the error message, the cluster name was empty/could not be retrieved from the Windows nodes causing the check to fail as expected. Specifying `datadog.clusterName` ensures a cluster name is provided to Agent pods.
