### ISSUE TITLE
Set hostname

### ISSUE THREAD

**Issue by djtecha** [DataDog/helm-charts#162]
Curious how we are supposed to set the hostname value for the agent pods? I'm getting errors like this in my logs because it's appending the clustername or something to the instance ip.

```
ValidHostname: ip-182-18-195-41.ec2.internal-prod_k8s_test is not RFC1123 compliant
```

**Comment by ahmed-mez** [comment]
Hi @djtecha 

The Datadog Agent appends the cluster name to the hostname to ensure that the hostname is unique for every host in your infrastructure.

In addition, the hostname must be `RFC1123` compliant indeed and you're seeing the error because of the underscores in your cluster name.

As a workaround, you can try to update the cluster name via the `datadog.clusterName` field in the helm chart: `prod-k8s-test` instead of `prod_k8s_test` for example.

Let us know if this works.

Thanks!
