### ISSUE TITLE
How to set apiKey and appKey from a file instead of environment variable or secret

### ISSUE THREAD

**Issue by kiich** [DataDog/helm-charts#200]
This may be a bit of edge case and i've read through the doc and couldn't see it mentioned so asking here.

We are deploying DD using the helm chart BUT what we want to do is retrieve the apiKey and appKey from Vault at runtime.

We use Vault for all things secrets including keys and stuff so initially we thought we can do the same for Datadog.
We managed to do this for the DD cluster-agent by doing something like: (in pseudo code):

1. Using vault agent injector, retrieve the secrets (being the api key and app key) from vault
2. dump that into a file on file system that DD pod shares with the injector
3. source that file and run the cluster-agent using the CMD override of helm chart

This worked great and we wanted to try the same mechanism for DD agent - however we found out that no such helm value override for CMD exist.

Are we trying to do something that is super edge case?

FYI the cluster-agent helm values file we use:
```
          clusterAgent:
            command: ['/bin/bash', '-c', 'source /vault/secrets/datadog.txt && /entrypoint.sh datadog-cluster-agent start']
```
where the datadog.txt file has:
```
                export DD_API_KEY="abc"
                export DD_APP_KEY="123"
```

**Comment by L3n41c** [comment]
Hello @kiich,

The Datadog agent has a feature which is dedicated to fetch secrets like the API key or the APP key from a secret store like Vault.
[Here is the corresponding documentation](https://docs.datadoghq.com/agent/guide/secrets-management).
The mechanism is very generic so that you can implement secret reads from anything.
The `datadog-agent` repository contains [an example of a secret provider that reads them from a file](https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/secrets-helper/readsecret.py) but the recommended way for you to go would be to implement your own secret backend directly reading Vault.

**Comment by kiich** [comment]
Thanks for this info @L3n41c - I saw this `secret-helper` folder and was curious what its intention was!
Will have a read of this and compare if this is easier to implement than a separate binary approach.
