### ISSUE TITLE
DD_TAGS wrongly parsed?

### ISSUE THREAD

**Issue by carlosjgp** [DataDog/helm-charts#305]
**Describe what happened:**
Missing tags after migration. See #304

Noticed this... comma separated vs space separated
- https://github.com/DataDog/dd-opentracing-cpp/blob/b7c44dbd942bb064dac75b66d76b5d97f79a3f3c/test/tracer_options_test.cpp#L64
- https://github.com/DataDog/helm-charts/blob/705fef59823035b8c7cde2c6092270963f65aa18/charts/datadog/templates/_containers-common-env.yaml#L35

**Describe what you expected:**
Metrics have common tags

**Steps to reproduce the issue:**
See #304 

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by clamoriniere** [comment]
Hello @carlosjgp 

Thanks for reporting this issue.
The problem described in the issue #304 is not due to a "datadog.tags" parsing problem (see PR #306).

For info, the datadog agents deployed with this helm chart is supporting the `space-separator` for the `DD_TAGS` envvar. but it is true, that some other datadog libraries are sometime using the `commas-separator` for the same envvar. We are working to support both everywhere to provide a consistent and backward configuration solution.
