### ISSUE TITLE
Use new kube-state-metrics Helm chart

### ISSUE THREAD

**Issue by tokyowizard** [DataDog/helm-charts#307]
As reported in https://github.com/DataDog/helm-charts/issues/151, the KSM helm chart moved. But the KSM helm chart has moved yet [again](https://github.com/kubernetes/kube-state-metrics/releases/tag/kube-state-metrics-helm-chart-2.13.3)!

The current [`requirements.yaml`](https://github.com/DataDog/helm-charts/blob/a73c03b920ab1a930199b7c90738ca535295e24b/charts/datadog/requirements.yaml#L9-L10) is pointing to the version, `2.13.2`, of the [KSM helm chart](https://github.com/kubernetes/kube-state-metrics/blob/ba36af0daecc2979657ccec784c0a1e600b9d1e1/charts/kube-state-metrics/Chart.yaml#L9-L10) that specifies KSM version `1.9.8`. The new location of the KSM helm chart is [here](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics).

We'd like to be on KSM version 2+ because:
* We're on AWS EKS 1.20 and KSM 2+ has full support for 1.20. See KSM [compatibility matrix](https://github.com/kubernetes/kube-state-metrics/#compatibility-matrix)
* We'd like to enable Datadog's [Kubernetes State Metrics Core](https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm)

**Comment by clamoriniere** [comment]
Hello,

Thanks for opening this issue. 

We are aware of this new move :) We have plan to use the new repo and the version [2.13.2](https://github.com/prometheus-community/helm-charts/releases/tag/kube-state-metrics-2.13.2). But it is not a real urgence since no new `ksm v1.9.x` as been released yet.

But, we will not update this dependency on any major version (3.x.x) for 2 reasons:
* the `kubernetes_state` check is only compatible with kube-state-metrics v1.x.x, so keeping the kube-state-metrics chart version to `v2.13.2.` allow use to use the image version `1.9.8`. This is to keep the metrics backward compatibility for user.
* the new `kubernetes_state_core` check is base and it expose the new KSM 2+ metrics, but doesn't require to deploy `kube-state-metrics` chart (more info in this [blog post](https://www.datadoghq.com/blog/kube-state-metrics-v2-monitoring-datadog/)).
  So if you plan to use the new check, you should not worry anymore about deploying and updating the `kube-state-metrics` chart with the `datadog` chart.

the  proper way to do so is to add the following configuration in your `values.yaml` file:

```yaml
datadog:
  # disable kube-state-metrics nested chart
  kubeStateMetricsEnabled: false
  # enable the new `kubernetes_state_core` check
  kubeStateMetricsCore:
    enabled: true
```

It will:
* uninstall (during an upgrade) or not install the `kube-state-metrics` chart.
* enable the `kubernetes_state_core` check.
* disable the autodiscovery of the `kubernetes_state` check. So if you would like to deploy on your own `kube-state-metrics` on the same cluster, it will not trigger the auto-discovery and the execution of the `kubernetes_state` check.

Please let us know if I answered to your question, and if the solution that we propose works for you.

Cheers
Cedric

**Comment by clamoriniere** [comment]
Please reopen the issue, it you need more information
