### ISSUE TITLE
Missing s6-run volumeMount in process-agent container

### ISSUE THREAD

**Issue by liorrozen** [DataDog/helm-charts#31]
**Describe what happened:**
[Network Performance Monitoring](https://docs.datadoghq.com/network_performance_monitoring/) was unable to report to datadog because of a missing volumeMount configuration (s6-run) in the process-agent container.

**Describe what you expected:**
I expect that the `process-agent` container will have all required configuration needed to facilitate [Network Performance Monitoring](https://docs.datadoghq.com/network_performance_monitoring/)

**Steps to reproduce the issue:**
Install the helm chart and enable the system-probe container

**Additional environment details (Operating System, Cloud provider, etc):**
We're running `k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26` (ami-06e67726ce5e65ca7).
Here is the output of `uname -a` on one of our hosts in the cluster:

`Linux ip-192-168-2-159 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux`

**Comment by clamoriniere** [comment]
Hi @liorrozen 
Thanks for opening this issue.
Looking at the support ticket, Your initial issue seams that the communication between the `process-agent` and the `system-probe` container didn't work.
This communication between the 2 process are done thanks to a socket that it should be shared between the 2 processes thanks to a [shared volume](https://github.com/DataDog/helm-charts/blob/2a7dedb52a9edc1a8394063b759732c25e85fe8f/charts/datadog/templates/daemonset-volumes-linux.yaml#L42) `sysprobe-socket-dir` (emptyDir)

So what I understand is that the problem is not that `run-s6` is not mounted in the `process-agent` container, but the `system-probe.socket` is not created in `/var/run/sysprobe` which correspond to the shared `emptyDir`.

Now we need to understand why it is the case :)

**Comment by liorrozen** [comment]
Hi @clamoriniere - thanks for your response. We don't have anything overriding the system-probe parameter, I used the  charts in this repo and didn't made any changes.

**Comment by liorrozen** [comment]
We've elected not to continue with NPM so this PR is no longer relevant to us. Closing for now
