### ISSUE TITLE
Custom EU Url insufficient for sending substantial amount of metrics Data Dog

### ISSUE THREAD

**Issue by Rambatino** [DataDog/helm-charts#314]
Set the `datadog.dd_url` variable to point to EU, however it doesn't add the correct env var for, say, the logs output. 

You still end up with:

```
failed to post http payload. code=403 host=agent-http-intake.logs.datadoghq.com response={}
```

This issue here: https://github.com/DataDog/datadog-agent/issues/6066 implied it needs to also change the `DATADOG_HOST` env var in the agent.

I checked the pod and all that is being set it:

```
DD_DD_URL=https://app.datadoghq.eu
```

(which actually doesn't look correct), but without diving into the code I'm not sure what the correct approach is.

**Comment by L3n41c** [comment]
Hello,

`datadog.dd_url` affects only the metrics endpoint and not the other ones.

[Here is the semantic of this setting](https://github.com/DataDog/datadog-agent/blob/7af555228d9a464dc5028d3e749c069f3ffe4d2c/pkg/config/config_template.yaml#L22-L29):
```
## @param dd_url - string - optional - default: https://app.datadoghq.com
## @env DD_URL - string - optional - default: https://app.datadoghq.com
## The host of the Datadog intake server to send metrics to, only set this option
## if you need the Agent to send metrics to a custom URL, it overrides the site
## setting defined in "site". It does not affect APM, Logs or Live Process intake which have their
## own "*_dd_url" settings.
#
# dd_url: https://app.datadoghq.com
```

If you need to have the agent send all its data like logs for ex. and not only metrics to EU instead of US, `datadog.site` is a more suitable parameter as it will affects all endpoints.

[Here is the description of this setting](https://github.com/DataDog/datadog-agent/blob/7af555228d9a464dc5028d3e749c069f3ffe4d2c/pkg/config/config_template.yaml#L13-L20):
```
## @param site - string - optional - default: datadoghq.com
## @env DD_SITE - string - optional - default: datadoghq.com
## The site of the Datadog intake to send Agent data to.
## Set to 'datadoghq.eu' to send data to the EU site.
## Set to 'us3.datadoghq.com' to send data to the US3 site.
## Set to 'ddog-gov.com' to send data to the US1-FED site.
#
# site: datadoghq.com
```

**Comment by Rambatino** [comment]
Thank-you!
