### ISSUE TITLE
Agent's kube-state-metrics spams log on K8s 1.22

### ISSUE THREAD

**Issue by mologie** [DataDog/helm-charts#415]
**Describe what happened:**

Hi!

I updated K8s from 1.21 to 1.22 while having Datadog Agent chart 2.22.15 (latest at time of writing) installed.

Since the update the following two log entries appear every few seconds:

```
k8s-testing-worker-1-testing | kube-state-metrics | pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta1.CertificateSigningRequest: the server could not find the requested resource
k8s-testing-worker-1-testing | kube-state-metrics | pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
```

kube-state-metrics is installed by Datadog Agent so I am reporting the issue here (assuming this is a configuration issued by Datadog Agent or an outdated version).

**Describe what you expected:**

There should be no log spam.

**Steps to reproduce the issue:**

1. Install Datadog agent with chart version 2.22.15 on K8s 1.21
2. Update to K8s 1.22

**Additional environment details (Operating System, Cloud provider, etc):**

Talos 0.13 under VMware

**Comment by mologie** [comment]
Please discard this, the solution was as simple as deleting kube-state-metric's Pod. => This is likely a bug in the upstream project. Sorry for the noise!

**Comment by mologie** [comment]
Reopening, the spam unfortunately continued after a few minutes. Datadog currently ships with kube-state-metrics 1.9.8 from last February, and I suspect that it simply does not support K8s 1.22 and you need to update it.

Workaround: Edit the kube-state-metrics deployment and remove the collectors=ingress and collectors=certificatesigningrequest arguments.

**Comment by clamoriniere** [comment]
Hello @mologie,

On Kubernetes 1.22, I will recommend to use the `kubernetes_state_core` check instead of `kubernetes_state`.

* the `kubernetes_state` check that you currently use and that requires `kube-state-metrics` chart installation, is only compatible with `kubernetes-state-metrics` version <= 1.9.x. And so the compatibility with Kubernetes v1.22 is limited since some resources is now gone in this new Kubernetes version.

* the `kubernetres_state_core` check is base on `kube-state-metrics` v2.x.x, and doesn't require anymore to deploy the  `kube-state-metrics` chart. more information about this new check that replaces `kubernetes_state` is available in the [documentation](https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm) and in this [blogpost](https://www.datadoghq.com/blog/kube-state-metrics-v2-monitoring-datadog/)

So to enable this new check, and disable the `kube-state-metrics` chart deployment, you can add in your `values.yaml` the following options:

```yaml
datadog:
  // ...
  kubeStateMetricsEnabled: false # to avoid deploying kube-state-metrics chart
  kubeStateMetricsCore:
    enabled: true # to enable the new `kubernetes_state_core` check
```
