### ISSUE TITLE
[question] Why does DD_EXTRA_CONFIG_PROVIDERS not set clusterchecks though ClusterChecks enabled?

### ISSUE THREAD

**Issue by kyontan** [DataDog/helm-charts#442]
**Describe what happened:**

When I set `clusterChecksRunner.enabled` to `true`, I expected `DD_EXTRA_CONFIG_PROVIDERS` to have included `clusterchecks`, but not.

To understand its behavior, I found following conditions:

https://github.com/DataDog/helm-charts/blob/d5e1f4370442bdc5e457468ac7ff0ff943f528d5/charts/datadog/templates/_container-agent.yaml#L82-L88

`(and (not .Values.existingClusterAgent.join) .Values.clusterChecksRunner.enabled)`

Since `existingClusterAgent.join` is `false` by default and I set `clusterChecksRunner.enabled` to `true`, it evaluates `true`, therefore `DD_EXTRA_CONFIG_PROVIDERS` become `"endpointschecks"`, not `"clusterchecks endpointschecks"`.

**Describe what you expected:**

I expected `DD_EXTRA_CONFIG_PROVIDERS` become `"clusterchecks endpointschecks"` regardless `existingClusterAgent.join` is false or true.

I read [docs](https://docs.datadoghq.com/agent/cluster_agent/clusterchecks/) and I thought that the `DD_EXTRA_CONFIG_PROVIDERS` should include `clusterchecks` when we enabled a Cluster Agent.

**Steps to reproduce the issue:**

helm input:
```yaml
datadog:
  clusterChecks:
    enabled: true
clusterChecksRunner:
  enabled: true
```

**Additional environment details (Operating System, Cloud provider, etc):**

Chart version: 2.23.6

**Comment by clamoriniere** [comment]
Hello,

When `.Values.clusterChecksRunner.enabled: true` a dedicated Deployment is create to deploy Agent specialised for running cluster checks. Thanks to it, Agent deployed on each node (daemonset) are not impacted by the procession of cluster-check. 
We still set `DD_EXTRA_CONFIG_PROVIDERS=endpointschecks` because we want to have checks configured thanks to "endpoints check" configurations scheduled on the same Node than the pod targeted by the endpoints check. Thanks to it, the endpoint check data are properly tagged with Pod/Containers information.

About `.Values.existingClusterAgent.join` we introduce this parameter to support Windows Nodes. The idea is to first: creates a `datadog` chart deployment release that target the linux Nodes (deployed with the ClusterAgent). Then you create a new release of the chart to target the Windows Node. 
And because some check configured with cluster check might not run properly on windows node. The chart protect the user to have `clusterchecks` configured on Agent Node when `.Values.existingClusterAgent.join:true`. [full doc](**url**)

This restriction can be alleviated, if we know a use case that needs it.

@kyontan could you explain us what you would like to change this behaviour. Could you explain your use case? 🙇

**Comment by levan-m** [comment]
Resolving since we haven't received any update. Feel free to reopen if the problem arises.
