### ISSUE TITLE
The `namespace` is always `default` and no way to override it

### ISSUE THREAD

**Issue by nitrocode** [DataDog/helm-charts#485]
**Describe what happened:**
The `namespace` is always `default`

**Describe what you expected:**
I'd like the charts to reflect the correct namespace given to it by helm

Why is `metadata.namespace` even defined ?

> In general, templates should not define a namespace. This is because Helm installs objects into the namespace provided with the --namespace flag. By omitting this information, it also provides templates with some flexibility for post-render operations (like helm template | kubectl create --namespace foo -f -)

Source https://github.com/helm/helm/issues/5465#issuecomment-473942223

If it has to be defined, then we should at least allow overriding the namespace with a value.

```yaml
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
```

**Steps to reproduce the issue:**
helm install --namespace monitoring datadog-agent datadog/datadog

**Additional environment details (Operating System, Cloud provider, etc):**
* https://stackoverflow.com/questions/68142933/how-to-override-the-release-namespace-for-subcharts
* https://github.com/helm/helm/issues/5465
* Previous issue: https://github.com/DataDog/helm-charts/issues/217

**Comment by clamoriniere** [comment]
Hi @nitrocode 

Thanks for opening this issue.

I looked to several template file in the `datadog/datadog` chart and it uses `.Release.namespace`. So `helm install --namespace monitoring` should install properly the datadog agents in the `monitoring` namespace.

So the title of the issue seems not valid to me.

From what I understand, you want to be able to install the chart in a specific namespace based on an option in the `values.yaml`. Is that correct?

**Comment by nitrocode** [comment]
@clamoriniere ah you were right. PEBKAC. Thank you.
