### ISSUE TITLE
How to set values in datadog.yaml?

### ISSUE THREAD

**Issue by irl-segfault** [DataDog/helm-charts#591]
According to the docs on datadog agent config, in v6 and beyond the method of configuring the datadog agent is a YAML file located at `/etc/datadog-agent/datadog.yaml`

The `datadog` helm chart has a `values.yaml` file, but it's not clear which values ultimately end up in `/etc/datadog-agent/datadog.yaml`.

The docs do say that the Daemonset agent deployed via Helm uses environment variables as configuration, and these are clearly traceable from the Helm chart `values.yaml` file into the Daemonset env variables. 

Specifically, I want to know how to set the field `ec2_prefer_imdsv2` to be `true` instead of the default of `false`.  Would this be achieved by setting an environment variable on the pod `DD_EC2_PREFER_IMDSV2`?

Thanks for the help!

**Comment by irl-segfault** [comment]
in general, my question is -- how do we set agent configuration values that aren't directly exposed in some part of the Helm chart `values.yaml` file, such as `ec2_prefer_imdsv2`?

**Comment by mohsiur** [comment]
@irl-segfault Were you able to find a solution to this, facing a similar issue.

**Comment by kaitlavs** [comment]
Hi there @irl-segfault 

If you wish to configure specific parameters for the `datadog.yaml` file in the helm chart specifically, you can make use of the `agents.customAgentConfig` parameter: https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml#L1236-L1258

Otherwise, a majority of the parameters you find in the `datadog.yaml` file can be used as environment variables. As you suggested, if you are looking to enable `ec2_prefer_imdsv2`, than you can set the env var `DD_EC2_PREFER_IMDSV2` to true in the `datadog.env` parameter of the helm chart: https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml#L315-L320. This will set this env var on all the containers in the agent pod.

Example:

```
datadog:
  [...]
  env:
    - name: DD_EC2_PREFER_IMDSV2
      value: true
```
