### ISSUE TITLE
Kube-State-Metrics Dependency Very Old

### ISSUE THREAD

**Issue by sam-cogan** [DataDog/helm-charts#620]
**Describe what happened:**
The DataDog Helm chart has Kube-State-Metrics added as a dependency in requirements.yaml, however, the version here is very old, over a year.
```
  - name: kube-state-metrics
    version: 2.13.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: datadog.kubeStateMetricsEnabled
```

The current release is 4.7.0. As you might expect, when trying to install this chart our security scanner picks up a large number of vulnerabilities on this very old image.

**Describe what you expected:**

Dependencies versions to be upgraded regularly to keep up to date

**Steps to reproduce the issue:**

View https://github.com/DataDog/helm-charts/blob/main/charts/datadog/requirements.yaml 

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by nicoodle** [comment]
To add to this, the version of kube-state-metrics deployed does not support more recent versions of Kubernetes resulting in the logs being flooded with messages like the following:

`pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)`

**Comment by clamoriniere** [comment]
Hi @sam-cogan and @nicoodle 

I [explained](https://github.com/DataDog/helm-charts/pull/623#issuecomment-1128782060) in the related pull request the reason why we haven't updated the `kube-state-metrics` chart dependency.

**Comment by jscarrott** [comment]
Is there any plan to fix this? It is currently preventing our scheduled upgrades of the clusters using datadog which is annoying. Still, the EOL of 1.21 is coming up and at that point, the upgrade will happen anyway and I don't know what will happen to datadog.

**Comment by clamoriniere** [comment]
Hi @jscarrott 

The plan is to remove the kube-state-metrics chart dependency in our next major chart version.

Because we already provide a replacement solution for generating the `kubernetes_state.*` metrics without the needs to deploy `kube-state-metrics`: we have build a new integration call [kubernetes_state_core](https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm) that replace our previous `kubernetes_state` check.

you can find more details about why we have decided to make a new check instead of relying on `kube-state-metrics`  v2 chart.

To use the new check and disable the `kube-state-metrics` chart installation, the option to add in your values.yaml are:

```yaml
datadog:
...
  kubeStateMetricsEnabled: false # disable the `kube-state-metrics` chart dep installation.
  kubeStateMetricsCore:
    enabled: true                # enable the new check
```
