### ISSUE TITLE
GKE otel receivers on Autopilot don't work due to hostPort

### ISSUE THREAD

**Issue by arirubinstein** [DataDog/helm-charts#750]
The helm chart for datadog-agent doesn't work out of the box with GKE Autopilot when using `.datadog.otlp.receiver.protocols.http/grpc.enabled = true`
due to it utilizing hostPort as the method of exposure.  

I was able to work around this by making hostPort conditional for these two endpoints, and additionally adding a service in `agent-services.yaml` to be able to use the clusterIP to report otel metrics:
```helm
{{- if  .Values.datadog.otlp.receiver.protocols.grpc.enabled }}
    - protocol: TCP
      port: {{ .Values.datadog.otlp.receiver.protocols.grpc.endpoint | regexFind ":[0-9]+$" | trimPrefix ":" }}
      targetPort:  otlpgrpcport
      name: otlpgrpcport
{{- end }}
{{- if .Values.datadog.otlp.receiver.protocols.http.enabled }}
    - protocol: TCP
      port: {{ .Values.datadog.otlp.receiver.protocols.http.endpoint | regexFind ":[0-9]+$" | trimPrefix ":" }}
      targetPort:  otlphttpport
      name: otlphttpport
{{- end }}

```

**Comment by ejtriple** [comment]
@arirubinstein Our team is currently running into this same issue. Can you be a bit more specific about what actions you had to take? I tried converting the hostport to a nodeport, and am not able to establish a connection from our pod to the datadog agent.

**Comment by JacksonDavenport** [comment]
Hello, those changes were essentially what we had done in our `3.1.11` version of our Helm Chart with respect to the PR here:

- https://github.com/DataDog/helm-charts/pull/792

Where you can set the `useHostPort` flag under these protocols to disable that.

```yaml
datadog:
  #(...)
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
          useHostPort: false
        http:
          enabled: true
          useHostPort: false
```

As well as added the ability to use the `Service` created by the Helm chart to route this data instead of the `HostIP:HostPort` method. You can see a sample of that in that linked PR for setup.

**Note:** There is currently an issue with the latest version of the Helm Chart for GKE Autopilot to be fixed soon by (https://github.com/DataDog/helm-charts/pull/817). So if you want to test that specifically you can `helm upgrade ... --version 3.1.11` until that is merged.
