### ISSUE TITLE
[datadog] Allow mounting secret files to confd directory

### ISSUE THREAD

**Issue by MeNsaaH** [DataDog/helm-charts#800]
**Describe what happened:**
Prior to version 3.0.0, I could mount secrets directly to the datadog clusteragent pods at `/confd` with my configs such as postgres and mysql database configs. Right now with the new setup, I cannot do that becaus `kubeStateMetricsCore` already mounts on the same directory without allowing for extra mounts.

**Describe what you expected:**
I expect the chart to allow mounting extra files to `/confd` without any issues. I guess this can be solved by using projected volumes or volume subpaths.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by clamoriniere** [comment]
HI @MeNsaaH,

I was looking at your PR, but before reviewing it, can we review your need here, because we might have some solutions to propose with existing cluster-agent features.

First I think what you want to achieve is clear to me, and I understand why it doesn't work with the way we mount the conf.d configmap.

Let me explain why we do it like this: 
* we want to trigger a redeployment of the cluster-agent if one of the conf.d files have changed so looking at only one config map that we generate allows to create an configmap "hash" annotation on the cluster-agent's `Deployment.Spec.Template`. 
* and to be honest, we didn't imagine at that time a use case like yours.

To manage secret information we usually recommend using the agent/cluster-agent [secret backend feature](https://docs.datadoghq.com/agent/guide/secrets-management/?tab=linux). We have recently add the support of `Kubernetes secret` in the secret backend implementation provided in the agent/cluster-agent.

If you set
 
```yaml
datadog:
  secretBackend:
    command: "/readsecret_multiple_providers.sh"
```

you will be able to store sensitive information into a secret, but use the configmap to store the confd configuration. [Here is the doc about how to reference a kubernetes secret with the secretbackend `ENC[]` placeholder](https://docs.datadoghq.com/agent/guide/secrets-management/?tab=linux#script-for-reading-from-multiple-secret-providers).

Please let us know if this solution can fit your needs 🙇

**Comment by MeNsaaH** [comment]
@clamoriniere  seems to be what I was looking for. I'll try out the secret backend feature and see how that goes

**Comment by MeNsaaH** [comment]
@clamoriniere that worked perfectly. Thanks for the info. I'll be closing the PR in favor of this solution. Do let me know if you want me to reopen that

**Comment by clamoriniere** [comment]
@MeNsaaH 
Awesome 😃 
Yes please close the PR, and this issue.
