### ISSUE TITLE
datadog latest helm chart support very old version of kube-state-metrics

### ISSUE THREAD

**Issue by os14** [DataDog/helm-charts#865]
**Describe what happened:**
datadog latest helm chart (3.6.6) support very old version of kube-state-metrics helm chart (2.13.2).
this is turn into an issue because this kube-state-metrics version support the installation of kube-state-metrics image (v1.9.8).
this old kube-state-metrics version is supported on the following kubernetes versions:
<img width="872" alt="image" src="https://user-images.githubusercontent.com/17493790/209962918-b297185d-248f-45d9-ac9f-55988f07b45a.png">

this is a problem because kubernetes is already at 1.26, this issue is preventing us from upgrading to newer versions of kubernetes as can be seen here:
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/17493790/209963113-2519fed2-d4fa-4a91-85c8-817ce8b071d3.png">

**Describe what you expected:**
We would expect that the next version of datadog chart will support a newer kube-state-metrics helm chart.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by clamoriniere** [comment]
Hi @gerbal 

It is not requires anymore to install the `kube-state-metrics` chart with the `datadog` chart. we keep it as an option for backward compatibility and easy migration to the new `kubernetes_state_core` check. The new check provides a replacement solution for generating the `kubernetes_state.*` metrics without the needs to deploy `kube-state-metrics`. And it is based on `kube-state-metrics` v2+.

Since the version 3.0.0 of this chart. [kubernetes_state_core](https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm)  is enabled by default. and the `kube-state-metrics` chart deployment is disable by default. The plan is to remove the `kube-state-metrics` chart dependency in our next major chart version (v4.0.0).

you can find more details about why we have decided to make a new check instead of relying on `kube-state-metrics`  v2 chart is this blogpost: https://www.datadoghq.com/blog/kube-state-metrics-v2-monitoring-datadog/

To use the new check and disable the `kube-state-metrics` chart installation, the options to add in your values.yaml are:

```yaml
datadog:
...
  kubeStateMetricsEnabled: false # disable the `kube-state-metrics` chart dep installation.
  kubeStateMetricsCore:
    enabled: true                # enable the new check
```

As I said previously, it should be the default now since v3.0.0. But maybe some previous values are present in the `values.yaml` that is use for your deployment on GKE.

Please let us know if it's solve the deployment issue.

**Comment by gerbal** [comment]
:pray: Thanks @clamoriniere we were unaware of this change. Disabling `kubeStateMetricsEnabled` resolved the issue for us.
