### ISSUE TITLE
Observability Pipeline Worker

### ISSUE THREAD

**Issue by NasAmin** [DataDog/helm-charts#902]
**Describe what happened:**
Just saw the Observability Pipeline worker. What about orgs using Vector directly? How can they get observability pipelines enabled into their existing deployments of Vector?

**Describe what you expected:**
Vector supporting Observability Pipelines instead of a separate fork

**Steps to reproduce the issue:**
N/A

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by binarylogic** [comment]
Hey @NasAmin, you're very observant 😆 . You are correct, we will be powering the Observability Pipelines (OP) exclusively with the OP Worker, and Vector users will need to transition if they want to use OP. We intend to make the transition as easy as possible (you'll be able to drop in your Vector config and go). The OP Worker will bring many "upgrades" to Vector that are specific to using the OP product and would not make sense to add in Vector directly. For example, [Sensitive Data Scanner](https://www.datadoghq.com/product/sensitive-data-scanner/) is being integrated into the OP Worker so that you can redact sensitive data within your network.

That said, we are not taking the emphasis off of Vector and have big plans to continue improving it. We will also add a free Vector integration just like any other Datadog integration. It'll come with an OOTB dashboard, monitors, etc.

Let me know if that addresses your concerns/questions.

**Comment by NasAmin** [comment]
Thanks! Yes just wanted to clarify so we can decide our approach going forward.

**Comment by jszwedko** [comment]
Closing this since the question was answered.
